### ISSUE TITLE
clickhouse do not have data

### ISSUE THREAD

**Issue by DD152** [dioptra-io/zeph#29]
zeph traceroute finished, but clickhouse do not have traceroute data.
The result_measurement_uuid_agent table is null.
What should i do?
![image](https://github.com/dioptra-io/zeph/assets/42128210/ef581c27-14f5-46ae-92c4-79db7cf1c441)

my prefixes.txt 
```
pyasn_util_download.py --latest
zeph-bgp-convert --print-progress rib.20231119.0800.bz2 prefixes.txt
```

**Comment by DD152** [comment]
@matthieugouel Please help me!

**Comment by matthieugouel** [comment]
Hi! It seems that you are using Iris as your probing orchestrator. Do you use your own instance? 
If so, could you please paste the logs of the Iris worker/agent associated with your measurement?

**Comment by DD152** [comment]
> Hi! It seems that you are using Iris as your probing orchestrator. Do you use your own instance? If so, could you please paste the logs of the Iris worker/agent associated with your measurement?


@matthieugouel 
Yes, I use my own instance. But I looked everywhere, and I couldn't find logs in docker .  SO SORRY！Could  you tell me where logs is?  Or I can provide the server ip and password by email if you can help me find logs.
It's great to be able to communicate directly with developers! Thank you for your patience！

command：```zeph prefixes.txt --iris-base-url http://api.docker.localhost --iris-username admin@example.org --iris-password admin``` 
output：
16447375it [00:17, 934645.78it/s] 
INFO:zeph:file=prefixes.txt distinct-prefixes=11917849
INFO:httpx:HTTP Request: POST http://api.docker.localhost/auth/jwt/login "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET http://api.docker.localhost/users/me/services "HTTP/1.1 200 OK"
INFO:zeph:get-current-agents
INFO:httpx:HTTP Request: GET http://api.docker.localhost/agents?tag=all "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: GET http://api.docker.localhost/agents/?tag=all "HTTP/1.1 200 OK"
INFO:zeph:current-agents=['b7816383-2528-46b0-9663-bfe366bb27b6']
INFO:zeph:compute-budget
INFO:zeph:agent=b7816383-2528-46b0-9663-bfe366bb27b6 budget=2000
INFO:zeph:agent=b7816383-2528-46b0-9663-bfe366bb27b6 select-prefixes
INFO:zeph:agent=b7816383-2528-46b0-9663-bfe366bb27b6 upload-prefixes
INFO:httpx:HTTP Request: POST http://api.docker.localhost/targets "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: POST http://api.docker.localhost/targets/ "HTTP/1.1 201 Created"
INFO:zeph:agent=b7816383-2528-46b0-9663-bfe366bb27b6 key=zeph__b3a16ce3-348b-4b5f-b3e4-70a080af811c.csv
INFO:zeph:create-measurement
INFO:httpx:HTTP Request: POST http://api.docker.localhost/measurements "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: POST http://api.docker.localhost/measurements/ "HTTP/1.1 201 Created"
INFO:zeph:measurement_uuid=7dbda09a-307b-4a10-9b9d-a5e6ce64c51f

**Comment by DD152** [comment]
I could get logs by edit code. Let me tidy up the logs

**Comment by DD152** [comment]
@matthieugouel 
Everything seems to be normal. But the result table in clickhouse is still null.

command：```zeph prefixes.txt --iris-base-url http://api.docker.localhost --iris-username admin@example.org --iris-password admin```


worker logs:
![image](https://github.com/dioptra-io/zeph/assets/42128210/362fd7f0-a9f6-44ef-8ea9-26720c13393b)

agent logs:
![image](https://github.com/dioptra-io/zeph/assets/42128210/26e556d4-a6f2-40cc-987a-c2a70e3ad135)

**Comment by matthieugouel** [comment]
Hi, could you display the content of `prefixes.txt` (or at least the head) ?

**Comment by DD152** [comment]
> Hi, could you display the content of `prefixes.txt` (or at least the head) ?

my prefixes.txt
```
pyasn_util_download.py --latest
zeph-bgp-convert --print-progress rib.20231119.0800.bz2 prefixes.txt
```

> 1.0.0.0/24
1.0.4.0/24
1.0.5.0/24
1.0.6.0/24
1.0.7.0/24
1.0.5.0/24
1.0.16.0/24
1.0.32.0/24
1.0.64.0/24
···
223.255.241.0/24
223.255.242.0/24
223.255.243.0/24
223.255.244.0/24
223.255.245.0/24
223.255.246.0/24
223.255.247.0/24
223.255.248.0/24
223.255.249.0/24
223.255.250.0/24
223.255.251.0/24
223.255.252.0/24
223.255.253.0/24
223.255.254.0/24

**Comment by matthieugouel** [comment]
Ok. So from what I can see, everything seems fine so far. Did you try to do a measurement manually with your Iris instance? On a broader note, it seems that it is an issue with Iris (at least your instance) rather than Zeph. So it may be cleaner to create an issue on [dioptra-io/iris](https://github.com/dioptra-io/iris) repository with this issue attached. 

One thing I would check is if you receive the ICMP TTL exceeded replies on the agent (seems you don't). 
Maybe the agent is behind a NAT or a firewall that block ICMP? On our own instance, the agents directly has a public IP address. 
One test you could do is to perform a regular traceroute / ping from inside the agent container to see if it works.

**Comment by DD152** [comment]
Ok. I will check it and give feedback.
Close. Move to [iris #165](https://github.com/dioptra-io/iris/issues/165)
